/**
 * Export the local SQLite database to a D1-ready SQL file.
 *
 *   node scripts/export-d1.mjs > migrate.sql
 *
 * Passwords cannot be carried over (local = bcrypt, Workers = PBKDF2 via Web
 * Crypto), so every existing account gets TEMP_PASSWORD below.
 */

import Database from 'better-sqlite3';
import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');
const dbPath = path.join(projectRoot, 'data', 'iraq-dark.db');
const outPath = path.join(projectRoot, 'migrate.sql');

const TEMP_PASSWORD = process.argv[2] || process.env.MIGRATE_PASSWORD || '';
const PBKDF2_ITERATIONS = 100000;

// Insert parents before children so the script works with FKs enabled too.
const TABLE_ORDER = [
  'categories',
  'users',
  'user_profiles',
  'follows',
  'sessions',
  'topics',
  'replies',
  'notifications',
  'likes',
  'bookmarks',
  'topic_views'
];

function hashPassword(password) {
  const salt = crypto.randomBytes(16);
  const derived = crypto.pbkdf2Sync(password, salt, PBKDF2_ITERATIONS, 32, 'sha256');
  return `pbkdf2$${PBKDF2_ITERATIONS}$${salt.toString('base64')}$${derived.toString('base64')}`;
}

function literal(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'bigint') return String(value);
  if (Buffer.isBuffer(value) || value instanceof Uint8Array) {
    return `X'${Buffer.from(value).toString('hex')}'`;
  }
  if (typeof value === 'boolean') return value ? '1' : '0';
  return `'${String(value).replace(/'/g, "''")}'`;
}

if (!fs.existsSync(dbPath)) {
  console.error(`Local database not found: ${dbPath}`);
  process.exit(1);
}

if (!TEMP_PASSWORD || TEMP_PASSWORD.length < 8) {
  console.error('Usage: MIGRATE_PASSWORD=<at least 8 chars> node scripts/export-d1.mjs');
  console.error('(The password cannot be migrated from bcrypt — existing accounts are reset to it.)');
  process.exit(1);
}

const db = new Database(dbPath, { readonly: true });

const schema = db
  .prepare(
    "SELECT name, sql FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
  )
  .all();

const indexes = db
  .prepare("SELECT name, sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL ORDER BY name")
  .all();

const lines = [
  '-- IRAQ DARK: local SQLite -> Cloudflare D1',
  '-- Generated by scripts/export-d1.mjs',
  ''
];

for (const { sql } of schema) lines.push(`${sql.replace(/\s+/g, ' ').trim()};`, '');
for (const { sql } of indexes) lines.push(`${sql.replace(/\s+/g, ' ').trim()};`, '');

const columnsFor = table =>
  db.prepare(`PRAGMA table_info(${table})`).all().map(col => col.name);

for (const table of TABLE_ORDER) {
  const exists = schema.some(entry => entry.name === table);
  if (!exists) continue;

  const columns = columnsFor(table);
  const rows = db.prepare(`SELECT * FROM ${table}`).all();
  if (!rows.length) continue;

  lines.push(`-- ${table} (${rows.length} rows)`);

  for (const row of rows) {
    const values = columns.map(column => {
      if (table === 'users' && column === 'password_hash') return literal(hashPassword(TEMP_PASSWORD));
      return literal(row[column]);
    });

    lines.push(
      `INSERT INTO ${table} (${columns.map(c => `"${c}"`).join(', ')}) VALUES (${values.join(', ')});`
    );
  }

  lines.push('');
}

db.close();

fs.writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');

const counts = TABLE_ORDER
  .map(table => {
    try {
      return { table, rows: new Database(dbPath, { readonly: true }).prepare(`SELECT COUNT(*) c FROM ${table}`).get().c };
    } catch {
      return { table, rows: '-' };
    }
  })
  .filter(entry => entry.rows !== '-');

console.log(`Wrote ${outPath}`);
console.log(`Existing accounts now use password: ${TEMP_PASSWORD}`);
console.log(counts.map(entry => `  ${entry.table}: ${entry.rows}`).join('\n'));
